SELECT
    m.match_id,
    d.date                                                                    AS match_date,
    d.season,
    m.match_round_number,
    m.match_round_name,
    r.match_result                                                            AS result,
    at_dim.appearance_type,
    p.player_name,
    p.player_photo,
    t.team_name,
    t.team_logo,
    ts.team_side,
    ot.opponent_team_name,
    ot.opponent_team_short_name,
    dpos.position_group,
    dpos.position_name,
    dpos.position_short_code,
    df.formation,
    f.minutes_played,
    f.goals_scored,
    f.own_goals,
    f.assists,
    f.shots_total,
    f.shots_on_target,
    f.shots_off_target,
    f.shots_blocked,
    f.woodwork_hits,
    f.big_chances_created,
    f.chances_created,
    f.big_chances_missed,
    f.key_passes,
    f.passes_total,
    f.passes_accurate,
    round(f.passes_accurate::double / nullif(f.passes_total, 0) * 100, 1)    AS pass_accuracy,
    f.passes_final_third,
    f.long_balls,
    f.long_balls_won,
    f.dribbles_attempts,
    f.dribbles_completed,
    f.crosses_total,
    f.crosses_accurate,
    f.tackles,
    f.tackles_won,
    f.interceptions,
    f.clearances,
    f.clearances_off_line,
    f.aerials_won,
    f.aerials_lost,
    f.blocks,
    f.balls_recovered,
    f.last_man_tackle,
    f.duels_total,
    f.duels_won,
    f.duels_lost,
    f.times_dribbled_past,
    f.dispossessed,
    f.possession_losses,
    f.fouls_committed,
    f.fouls_drawn,
    f.saves,
    f.saves_inside_box,
    f.high_ball_claims,
    f.goalkeeper_punches,
    f.goals_conceded,
    f.penalty_won,
    f.penalty_committed,
    f.penalty_scored,
    f.penalty_missed,
    f.penalty_saved,
    f.offsides,
    f.yellow_cards,
    f.yellow_red_cards,
    f.red_cards,
    f.errors_leading_to_goal,
    f.errors_leading_to_shot,
    round(f.rating, 2)                                                        AS rating
FROM superligaen.gold.fct_player_appearances   f
JOIN superligaen.gold.dim_date                 d      ON d.date_sk               = f.date_sk
JOIN superligaen.gold.dim_match                m      ON m.match_sk              = f.match_sk
JOIN superligaen.gold.dim_player               p      ON p.player_sk             = f.player_sk
JOIN superligaen.gold.dim_team                 t      ON t.team_sk               = f.team_sk
JOIN superligaen.gold.dim_opponent_team        ot     ON ot.opponent_team_sk     = f.opponent_team_sk
JOIN superligaen.gold.dim_match_result         r      ON r.match_result_sk       = f.match_result_sk
JOIN superligaen.gold.dim_team_side            ts     ON ts.team_side_sk         = f.team_side_sk
JOIN superligaen.gold.dim_appearance_type      at_dim ON at_dim.appearance_type_sk = f.appearance_type_sk
JOIN superligaen.gold.dim_formation            df     ON df.formation_sk         = f.formation_sk
JOIN superligaen.gold.dim_position             dpos   ON dpos.position_sk        = f.position_sk
WHERE m.match_type = 'Group Stage'
  AND d.season >= '2020/21'
  AND at_dim.appearance_type IN ('Starter', 'Substitute')
