SELECT
    d.date                                                AS match_date,
    d.season,
    d.is_current_season,
    d.month_name,
    d.day_name,
    d.is_weekend,
    m.match_id,
    m.match_name,
    m.match_short_name,
    m.match_round_name,
    m.match_round_type,
    m.match_round_number,
    m.match_result                                        AS score,
    m.match_status,
    m.kick_off_time,
    p.player_id,
    p.player_name,
    p.player_firstname,
    p.player_lastname,
    p.player_nationality,
    p.player_birth_date,
    p.player_birth_place,
    p.player_birth_country,
    p.player_height,
    p.player_weight,
    p.player_photo,
    p.player_position,
    p.player_detailed_position,
    dpos.position_name,
    dpos.position_short_code,
    dpos.position_group,
    df.formation,
    t.team_name,
    t.team_short_name,
    t.team_code,
    t.team_logo,
    ot.opponent_team_name,
    ot.opponent_team_short_name,
    ot.opponent_team_code,
    ot.opponent_team_logo,
    r.match_result                                        AS result,
    ts.team_side,
    ref.referee_common_name                               AS referee_name,
    ref.referee_display_name,
    ref.referee_nationality,
    st.stadium_name,
    st.stadium_city,
    st.stadium_capacity,
    st.stadium_surface,
    st.stadium_latitude,
    st.stadium_longitude,
    dc.coach_name,
    at_dim.appearance_type,
    f.minutes_played,
    f.goals_scored,
    f.own_goals,
    f.assists,
    f.shots_total,
    f.shots_on_target,
    f.shots_off_target,
    f.shots_blocked,
    f.woodwork_hits,
    f.big_chances_created,
    f.big_chances_missed,
    f.chances_created,
    f.passes_total,
    f.passes_accurate,
    f.key_passes,
    f.passes_final_third,
    f.passes_backward,
    f.long_balls,
    f.long_balls_won,
    f.crosses_total,
    f.crosses_accurate,
    f.tackles,
    f.tackles_won,
    f.clearances,
    f.clearances_off_line,
    f.interceptions,
    f.aerials_won,
    f.aerials_lost,
    f.blocks,
    f.balls_recovered,
    f.last_man_tackle,
    f.duels_total,
    f.duels_won,
    f.duels_lost,
    f.dribbles_attempts,
    f.dribbles_completed,
    f.times_dribbled_past,
    f.dispossessed,
    f.fouls_committed,
    f.fouls_drawn,
    f.yellow_cards,
    f.yellow_red_cards,
    f.red_cards,
    f.offsides,
    f.penalty_won,
    f.penalty_committed,
    f.penalty_scored,
    f.penalty_missed,
    f.penalty_saved,
    f.goals_conceded,
    f.saves,
    f.saves_inside_box,
    f.goalkeeper_punches,
    f.high_ball_claims,
    f.errors_leading_to_goal,
    f.errors_leading_to_shot,
    f.possession_losses,
    f.rating
FROM superligaen.gold.fct_player_appearances  f
JOIN superligaen.gold.dim_date                d    ON d.date_sk           = f.date_sk
JOIN superligaen.gold.dim_match               m    ON m.match_sk          = f.match_sk
JOIN superligaen.gold.dim_player              p    ON p.player_sk         = f.player_sk
JOIN superligaen.gold.dim_team                t    ON t.team_sk           = f.team_sk
JOIN superligaen.gold.dim_opponent_team       ot   ON ot.opponent_team_sk = f.opponent_team_sk
JOIN superligaen.gold.dim_match_result        r    ON r.match_result_sk   = f.match_result_sk
JOIN superligaen.gold.dim_team_side           ts   ON ts.team_side_sk     = f.team_side_sk
JOIN superligaen.gold.dim_referee             ref  ON ref.referee_sk      = f.referee_sk
JOIN superligaen.gold.dim_stadium             st   ON st.stadium_sk       = f.stadium_sk
JOIN superligaen.gold.dim_appearance_type     at_dim ON at_dim.appearance_type_sk = f.appearance_type_sk
JOIN superligaen.gold.dim_formation           df     ON df.formation_sk           = f.formation_sk
JOIN superligaen.gold.dim_position            dpos   ON dpos.position_sk          = f.position_sk
JOIN superligaen.gold.dim_coach               dc     ON dc.coach_sk               = f.coach_sk
WHERE m.match_type = 'Group Stage'
  AND d.season >= '2020/21'
