danish_football:
  outputs:
    dev:
      type: duckdb
      path: "md:danish_football?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      schema: dev_danish_football
      threads: 4

    prod:
      type: duckdb
      path: "md:danish_football?motherduck_token={{ env_var('MOTHERDUCK_TOKEN') }}"
      schema: danish_football
      threads: 4

  target: dev
