WITH base AS (
    SELECT
        d.season_scotland AS season,
        MAX(d.is_current_season_scotland)                            AS is_current_season,
        p.player_name,
        p.player_photo,
        p.player_nationality,
        p.player_birth_date,
        p.player_height,
        p.player_weight,
        MAX(p.player_position)                              AS player_position,
        MAX(p.player_detailed_position)                     AS player_detailed_position,
        MAX(p.player_main_position)                         AS player_main_position,
        MAX(dpos.position_group)                            AS position_group,
        MAX(t.team_name)                                    AS team_name,
        MAX(t.team_logo)                                    AS team_logo,
        COUNT(DISTINCT m.match_id)                          AS matches,
        SUM(CASE WHEN at_dim.appearance_type = 'Starter' THEN 1 ELSE 0 END) AS starts,
        SUM(f.minutes_played)::int                          AS minutes_played,
        SUM(f.goals_scored)::int                            AS goals,
        SUM(f.assists)::int                                 AS assists,
        SUM(f.own_goals)::int                               AS own_goals,
        SUM(f.shots_total)::int                             AS shots_total,
        SUM(f.shots_on_target)::int                         AS shots_on_target,
        SUM(f.shots_off_target)::int                        AS shots_off_target,
        SUM(f.shots_blocked)::int                           AS shots_blocked,
        SUM(f.woodwork_hits)::int                           AS woodwork_hits,
        SUM(f.big_chances_created)::int                     AS big_chances_created,
        SUM(f.chances_created)::int                         AS chances_created,
        SUM(f.big_chances_missed)::int                      AS big_chances_missed,
        SUM(f.key_passes)::int                              AS key_passes,
        SUM(f.passes_total)::int                            AS passes_total,
        SUM(f.passes_accurate)::int                         AS passes_accurate,
        SUM(f.passes_final_third)::int                      AS passes_final_third,
        SUM(f.long_balls)::int                              AS long_balls,
        SUM(f.long_balls_won)::int                          AS long_balls_won,
        SUM(f.crosses_total)::int                           AS crosses_total,
        SUM(f.crosses_accurate)::int                        AS crosses_accurate,
        SUM(f.dribbles_attempts)::int                       AS dribbles_attempts,
        SUM(f.dribbles_completed)::int                      AS dribbles_completed,
        SUM(f.tackles)::int                                 AS tackles,
        SUM(f.tackles_won)::int                             AS tackles_won,
        SUM(f.interceptions)::int                           AS interceptions,
        SUM(f.clearances)::int                              AS clearances,
        SUM(f.clearances_off_line)::int                     AS clearances_off_line,
        SUM(f.balls_recovered)::int                         AS balls_recovered,
        SUM(f.aerials_won)::int                             AS aerials_won,
        SUM(f.aerials_lost)::int                            AS aerials_lost,
        SUM(f.blocks)::int                                  AS blocks,
        SUM(f.duels_total)::int                             AS duels_total,
        SUM(f.duels_won)::int                               AS duels_won,
        SUM(f.duels_lost)::int                              AS duels_lost,
        SUM(f.times_dribbled_past)::int                     AS times_dribbled_past,
        SUM(f.dispossessed)::int                            AS dispossessed,
        SUM(f.possession_losses)::int                       AS possession_losses,
        SUM(f.fouls_committed)::int                         AS fouls_committed,
        SUM(f.fouls_drawn)::int                             AS fouls_drawn,
        SUM(f.yellow_cards)::int                            AS yellow_cards,
        SUM(f.yellow_red_cards)::int                        AS yellow_red_cards,
        SUM(f.red_cards)::int                               AS red_cards,
        SUM(f.offsides)::int                                AS offsides,
        SUM(f.saves)::int                                   AS saves,
        SUM(f.saves_inside_box)::int                        AS saves_inside_box,
        SUM(f.goalkeeper_punches)::int                      AS goalkeeper_punches,
        SUM(f.high_ball_claims)::int                        AS high_ball_claims,
        SUM(f.goals_conceded)::int                          AS goals_conceded,
        SUM(f.penalty_won)::int                             AS penalty_won,
        SUM(f.penalty_committed)::int                       AS penalty_committed,
        SUM(f.penalty_scored)::int                          AS penalty_scored,
        SUM(f.penalty_missed)::int                          AS penalty_missed,
        SUM(f.penalty_saved)::int                           AS penalty_saved,
        SUM(f.errors_leading_to_goal)::int                  AS errors_leading_to_goal,
        SUM(f.errors_leading_to_shot)::int                  AS errors_leading_to_shot,
        SUM(f.last_man_tackle)::int                         AS last_man_tackle,
        SUM(CASE WHEN r.match_result = 'Win'  THEN 1 ELSE 0 END)::int AS wins,
        SUM(CASE WHEN r.match_result = 'Draw' THEN 1 ELSE 0 END)::int AS draws,
        SUM(CASE WHEN r.match_result = 'Loss' THEN 1 ELSE 0 END)::int AS losses,
        ROUND(AVG(f.rating), 2)                             AS avg_rating
    FROM superligaen.gold.fct_player_appearances   f
    JOIN superligaen.gold.dim_date                 d      ON d.date_sk               = f.date_sk
    JOIN superligaen.gold.dim_match                m      ON m.match_sk              = f.match_sk
    JOIN superligaen.gold.dim_player               p      ON p.player_sk             = f.player_sk
    JOIN superligaen.gold.dim_team                 t      ON t.team_sk               = f.team_sk
    JOIN superligaen.gold.dim_match_result         r      ON r.match_result_sk       = f.match_result_sk
    JOIN superligaen.gold.dim_appearance_type      at_dim ON at_dim.appearance_type_sk = f.appearance_type_sk
    JOIN superligaen.gold.dim_position             dpos   ON dpos.position_sk        = f.position_sk
    WHERE d.season_scotland >= '2020/21'
      AND r.match_result IN ('Win', 'Draw', 'Loss')
      AND f.league_sk = (SELECT league_sk FROM superligaen.gold.dim_league WHERE league_id = 501)  -- Premiership only
    GROUP BY
        d.season_scotland,
        p.player_name,
        p.player_photo,
        p.player_nationality,
        p.player_birth_date,
        p.player_height,
        p.player_weight
),
pct_input AS (
    SELECT
        season, player_name, avg_rating,
        goals * 90.0 / NULLIF(minutes_played, 0)                            AS goals_per90_r,
        assists * 90.0 / NULLIF(minutes_played, 0)                          AS assists_per90_r,
        shots_on_target * 90.0 / NULLIF(minutes_played, 0)                 AS sot_per90,
        100.0 * goals / NULLIF(shots_total, 0)                              AS shot_acc_pct,
        woodwork_hits * 90.0 / NULLIF(minutes_played, 0)                    AS woodwork_per90,
        big_chances_created * 90.0 / NULLIF(minutes_played, 0)             AS big_chances_per90,
        chances_created * 90.0 / NULLIF(minutes_played, 0)                 AS chances_per90,
        key_passes * 90.0 / NULLIF(minutes_played, 0)                       AS key_passes_per90,
        100.0 * big_chances_created / NULLIF(chances_created, 0)            AS chance_quality_pct,
        100.0 * crosses_accurate / NULLIF(crosses_total, 0)                AS cross_acc_pct,
        passes_final_third * 90.0 / NULLIF(minutes_played, 0)              AS passes_final_third_per90,
        100.0 * passes_accurate / NULLIF(passes_total, 0)                  AS pass_acc_pct,
        100.0 * dribbles_completed / NULLIF(dribbles_attempts, 0)          AS dribble_success_pct,
        100.0 * long_balls_won / NULLIF(long_balls, 0)                     AS long_ball_success_pct,
        (tackles + interceptions) * 90.0 / NULLIF(minutes_played, 0)       AS tkl_int_per90,
        100.0 * tackles_won / NULLIF(tackles, 0)                            AS tackle_success_pct,
        balls_recovered * 90.0 / NULLIF(minutes_played, 0)                 AS balls_recovered_per90,
        times_dribbled_past * 90.0 / NULLIF(minutes_played, 0)             AS times_dribbled_past_per90,
        errors_leading_to_goal * 90.0 / NULLIF(minutes_played, 0)          AS errors_per90,
        100.0 * duels_won / NULLIF(duels_total, 0)                          AS duel_win_pct_r,
        fouls_drawn * 90.0 / NULLIF(minutes_played, 0)                     AS fouls_drawn_per90_r,
        100.0 * aerials_won / NULLIF(aerials_won + aerials_lost, 0)         AS aerial_success_pct
    FROM base
    WHERE minutes_played >= 450
),
pct_ranks AS (
    SELECT
        season,
        player_name,
        ROUND((2 * PERCENT_RANK() OVER (PARTITION BY season ORDER BY goals_per90_r)
                 + PERCENT_RANK() OVER (PARTITION BY season ORDER BY assists_per90_r)
                 + PERCENT_RANK() OVER (PARTITION BY season ORDER BY sot_per90)
                 + PERCENT_RANK() OVER (PARTITION BY season ORDER BY shot_acc_pct)
                 + PERCENT_RANK() OVER (PARTITION BY season ORDER BY woodwork_per90)) / 6 * 100)        AS attacking_pct,
        ROUND((  PERCENT_RANK() OVER (PARTITION BY season ORDER BY chances_per90)
               + 2 * PERCENT_RANK() OVER (PARTITION BY season ORDER BY big_chances_per90)
               + PERCENT_RANK() OVER (PARTITION BY season ORDER BY key_passes_per90)
               + PERCENT_RANK() OVER (PARTITION BY season ORDER BY chance_quality_pct)
               + PERCENT_RANK() OVER (PARTITION BY season ORDER BY cross_acc_pct)
               + PERCENT_RANK() OVER (PARTITION BY season ORDER BY passes_final_third_per90)) / 7 * 100) AS creativity_pct,
        ROUND((2 * PERCENT_RANK() OVER (PARTITION BY season ORDER BY pass_acc_pct)
                 + PERCENT_RANK() OVER (PARTITION BY season ORDER BY dribble_success_pct)
                 + PERCENT_RANK() OVER (PARTITION BY season ORDER BY long_ball_success_pct)) / 4 * 100)  AS possession_pct,
        ROUND((2 * PERCENT_RANK() OVER (PARTITION BY season ORDER BY tkl_int_per90)
                 + PERCENT_RANK() OVER (PARTITION BY season ORDER BY tackle_success_pct)
                 + PERCENT_RANK() OVER (PARTITION BY season ORDER BY balls_recovered_per90)
                 + PERCENT_RANK() OVER (PARTITION BY season ORDER BY times_dribbled_past_per90 DESC)
                 + PERCENT_RANK() OVER (PARTITION BY season ORDER BY errors_per90 DESC)) / 6 * 100)      AS defending_pct,
        ROUND((2 * PERCENT_RANK() OVER (PARTITION BY season ORDER BY duel_win_pct_r)
                 + PERCENT_RANK() OVER (PARTITION BY season ORDER BY fouls_drawn_per90_r)
                 + PERCENT_RANK() OVER (PARTITION BY season ORDER BY aerial_success_pct)) / 4 * 100)     AS physicality_pct,
        ROUND(PERCENT_RANK() OVER (PARTITION BY season ORDER BY avg_rating) * 100)                       AS impact_pct
    FROM pct_input
)
SELECT
    b.season,
    b.is_current_season,
    b.player_name,
    b.player_photo,
    b.player_nationality,
    b.player_birth_date,
    b.player_height,
    b.player_weight,
    b.player_position,
    b.player_detailed_position,
    b.player_main_position,
    b.position_group,
    b.team_name,
    b.team_logo,
    b.matches,
    b.starts,
    b.minutes_played,
    b.goals,
    b.assists,
    b.own_goals,
    b.shots_total,
    b.shots_on_target,
    b.shots_off_target,
    b.shots_blocked,
    b.woodwork_hits,
    b.big_chances_created,
    b.chances_created,
    b.big_chances_missed,
    b.key_passes,
    b.passes_total,
    b.passes_accurate,
    b.passes_final_third,
    b.long_balls,
    b.long_balls_won,
    b.crosses_total,
    b.crosses_accurate,
    b.dribbles_attempts,
    b.dribbles_completed,
    b.tackles,
    b.tackles_won,
    b.interceptions,
    b.clearances,
    b.clearances_off_line,
    b.balls_recovered,
    b.aerials_won,
    b.aerials_lost,
    b.blocks,
    b.duels_total,
    b.duels_won,
    b.duels_lost,
    b.times_dribbled_past,
    b.dispossessed,
    b.possession_losses,
    b.fouls_committed,
    b.fouls_drawn,
    b.yellow_cards,
    b.yellow_red_cards,
    b.red_cards,
    b.offsides,
    b.saves,
    b.saves_inside_box,
    b.goalkeeper_punches,
    b.high_ball_claims,
    b.goals_conceded,
    b.penalty_won,
    b.penalty_committed,
    b.penalty_scored,
    b.penalty_missed,
    b.penalty_saved,
    b.errors_leading_to_goal,
    b.errors_leading_to_shot,
    b.last_man_tackle,
    b.wins,
    b.draws,
    b.losses,
    b.avg_rating,
    ROUND(b.goals * 90.0 / NULLIF(b.minutes_played, 0), 2)                                         AS goals_per90,
    ROUND(b.assists * 90.0 / NULLIF(b.minutes_played, 0), 2)                                        AS assists_per90,
    ROUND((b.goals + b.assists) * 90.0 / NULLIF(b.minutes_played, 0), 2)                            AS contributions_per90,
    ROUND(100.0 * b.passes_accurate / NULLIF(b.passes_total, 0), 1)                                 AS pass_accuracy,
    ROUND(100.0 * b.goals / NULLIF(b.shots_total, 0), 1)                                            AS shot_conversion,
    ROUND(100.0 * b.duels_won / NULLIF(b.duels_total, 0), 1)                                        AS duel_win_pct,
    (b.tackles + b.interceptions + b.balls_recovered)::int                                           AS def_actions,
    ROUND(100.0 * b.goals / NULLIF(b.shots_total, 0), 1)                                            AS shot_conv,
    ROUND(100.0 * b.crosses_accurate / NULLIF(b.crosses_total, 0), 1)                               AS cross_acc,
    ROUND(100.0 * b.dribbles_completed / NULLIF(b.dribbles_attempts, 0), 1)                         AS dribble_success,
    ROUND(100.0 * b.long_balls_won / NULLIF(b.long_balls, 0), 1)                                    AS long_ball_success,
    (b.tackles + b.interceptions)::int                                                               AS tkl_int,
    ROUND(100.0 * b.tackles_won / NULLIF(b.tackles, 0), 1)                                          AS tackle_success,
    ROUND(100.0 * b.aerials_won / NULLIF(b.aerials_won + b.aerials_lost, 0), 1)                     AS aerial_success,
    ROUND(b.fouls_drawn * 90.0 / NULLIF(b.minutes_played, 0), 2)                                    AS fouls_drawn_per90,
    p.attacking_pct,
    p.creativity_pct,
    p.possession_pct,
    p.defending_pct,
    p.physicality_pct,
    p.impact_pct
FROM base b
LEFT JOIN pct_ranks p ON p.season = b.season AND p.player_name = b.player_name
