-- Group 2 | refresh: season-scoped
-- {delete_filter} / {insert_filter} examples:
--   season-scoped : league_id = 119 AND season = 2025
--   full reload   : TRUE
CREATE SCHEMA IF NOT EXISTS {db}.silver;

CREATE TABLE IF NOT EXISTS {db}.silver.topscorers (
    season              INTEGER,
    league_id           INTEGER,
    player_id           INTEGER,
    player_name         VARCHAR,
    firstname           VARCHAR,
    lastname            VARCHAR,
    age                 INTEGER,
    birth_date          VARCHAR,
    birth_place         VARCHAR,
    birth_country       VARCHAR,
    nationality         VARCHAR,
    height              VARCHAR,
    weight              VARCHAR,
    injured             BOOLEAN,
    photo               VARCHAR,
    team_id             INTEGER,
    team_name           VARCHAR,
    team_logo           VARCHAR,
    appearances         INTEGER,
    lineups             INTEGER,
    minutes             INTEGER,
    shirt_number        INTEGER,
    position            VARCHAR,
    rating              VARCHAR,
    captain             BOOLEAN,
    sub_in              INTEGER,
    sub_out             INTEGER,
    sub_bench           INTEGER,
    shots_total         INTEGER,
    shots_on            INTEGER,
    goals               INTEGER,
    goals_conceded      INTEGER,
    assists             INTEGER,
    saves               INTEGER,
    passes_total        INTEGER,
    passes_key          INTEGER,
    passes_accuracy     VARCHAR,
    tackles_total       INTEGER,
    tackles_blocks      INTEGER,
    interceptions       INTEGER,
    duels_total         INTEGER,
    duels_won           INTEGER,
    dribbles_attempts   INTEGER,
    dribbles_success    INTEGER,
    dribbles_past       INTEGER,
    fouls_drawn         INTEGER,
    fouls_committed     INTEGER,
    yellow_cards        INTEGER,
    yellowred_cards     INTEGER,
    red_cards           INTEGER,
    penalty_won         INTEGER,
    penalty_committed   INTEGER,
    penalty_scored      INTEGER,
    penalty_missed      INTEGER,
    penalty_saved       INTEGER,
    ingested_at         TIMESTAMPTZ
);

DELETE FROM {db}.silver.topscorers WHERE {delete_filter};

INSERT INTO {db}.silver.topscorers
SELECT * FROM (
    SELECT
        season,
        league_id,
        (elem->>'$.player.id')::INTEGER              AS player_id,
        elem->>'$.player.name'                       AS player_name,
        elem->>'$.player.firstname'                  AS firstname,
        elem->>'$.player.lastname'                   AS lastname,
        (elem->>'$.player.age')::INTEGER             AS age,
        elem->>'$.player.birth.date'                 AS birth_date,
        elem->>'$.player.birth.place'                AS birth_place,
        elem->>'$.player.birth.country'              AS birth_country,
        elem->>'$.player.nationality'                AS nationality,
        elem->>'$.player.height'                     AS height,
        elem->>'$.player.weight'                     AS weight,
        (elem->>'$.player.injured')::BOOLEAN         AS injured,
        elem->>'$.player.photo'                      AS photo,
        (stats->>'$.team.id')::INTEGER               AS team_id,
        stats->>'$.team.name'                        AS team_name,
        stats->>'$.team.logo'                        AS team_logo,
        (stats->>'$.games.appearences')::INTEGER     AS appearances,
        (stats->>'$.games.lineups')::INTEGER         AS lineups,
        (stats->>'$.games.minutes')::INTEGER         AS minutes,
        (stats->>'$.games.number')::INTEGER          AS shirt_number,
        stats->>'$.games.position'                   AS position,
        stats->>'$.games.rating'                     AS rating,
        (stats->>'$.games.captain')::BOOLEAN         AS captain,
        (stats->>'$.substitutes.in')::INTEGER        AS sub_in,
        (stats->>'$.substitutes.out')::INTEGER       AS sub_out,
        (stats->>'$.substitutes.bench')::INTEGER     AS sub_bench,
        (stats->>'$.shots.total')::INTEGER           AS shots_total,
        (stats->>'$.shots.on')::INTEGER              AS shots_on,
        (stats->>'$.goals.total')::INTEGER           AS goals,
        (stats->>'$.goals.conceded')::INTEGER        AS goals_conceded,
        (stats->>'$.goals.assists')::INTEGER         AS assists,
        (stats->>'$.goals.saves')::INTEGER           AS saves,
        (stats->>'$.passes.total')::INTEGER          AS passes_total,
        (stats->>'$.passes.key')::INTEGER            AS passes_key,
        stats->>'$.passes.accuracy'                  AS passes_accuracy,
        (stats->>'$.tackles.total')::INTEGER         AS tackles_total,
        (stats->>'$.tackles.blocks')::INTEGER        AS tackles_blocks,
        (stats->>'$.tackles.interceptions')::INTEGER AS interceptions,
        (stats->>'$.duels.total')::INTEGER           AS duels_total,
        (stats->>'$.duels.won')::INTEGER             AS duels_won,
        (stats->>'$.dribbles.attempts')::INTEGER     AS dribbles_attempts,
        (stats->>'$.dribbles.success')::INTEGER      AS dribbles_success,
        (stats->>'$.dribbles.past')::INTEGER         AS dribbles_past,
        (stats->>'$.fouls.drawn')::INTEGER           AS fouls_drawn,
        (stats->>'$.fouls.committed')::INTEGER       AS fouls_committed,
        (stats->>'$.cards.yellow')::INTEGER          AS yellow_cards,
        (stats->>'$.cards.yellowred')::INTEGER       AS yellowred_cards,
        (stats->>'$.cards.red')::INTEGER             AS red_cards,
        (stats->>'$.penalty.won')::INTEGER           AS penalty_won,
        (stats->>'$.penalty.committed')::INTEGER     AS penalty_committed,
        (stats->>'$.penalty.scored')::INTEGER        AS penalty_scored,
        (stats->>'$.penalty.missed')::INTEGER        AS penalty_missed,
        (stats->>'$.penalty.saved')::INTEGER         AS penalty_saved,
        ingested_at
    FROM {db}.bronze.api_football__topscorers,
    UNNEST(raw_json::JSON[]) AS t1(elem),
    UNNEST((elem->'$.statistics')::JSON[]) AS t2(stats)
) _src WHERE {insert_filter};
